-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to labber;
-- GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO www;

DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  phone BIGINT NOT NULL
);
